title: Wocker
description: Wocker is a local WordPress development environment. Since itâ€™s based on Docker, it takes just 3 seconds to create every new installation of WordPress.

baseurl: ""
url: https://wocker.dev

exclude:
  - node_modules
  - gulpfile.js
  - gulpconfig.json
  - package.json
  - package-lock.json
  - npm-debug.log
  - README.md
  - LICENSE
  - config.rb

github:
  org: wckr
  repo: wocker
  admin: ixkaito
facebook:
  id: kite.koga
twitter:
  id: ixkaito

images_dir: /assets/images
css_dir: /assets/css
js_dir: /assets/js

ogp_image: /ogp-image.png

version: 1.4
